### ISSUE TITLE
github icon missing: please gen and release new version.

### ISSUE THREAD

**Issue by erlandsona** [icidasset/elm-material-icons#4]

**Comment by icidasset** [comment]
Hey! It doesn't look like there's a Github icon, where did you see that? 👀 
I updated the library and got this diff:

```
---- Material.Icons - MAJOR ----

    Added:
        align_horizontal_center : Material.Icons.Types.Icon msg
        align_horizontal_left : Material.Icons.Types.Icon msg
        align_horizontal_right : Material.Icons.Types.Icon msg
        align_vertical_bottom : Material.Icons.Types.Icon msg
        align_vertical_center : Material.Icons.Types.Icon msg
        align_vertical_top : Material.Icons.Types.Icon msg
        horizontal_distribute : Material.Icons.Types.Icon msg
        qr_code_2 : Material.Icons.Types.Icon msg
        update_disabled : Material.Icons.Types.Icon msg
        vertical_distribute : Material.Icons.Types.Icon msg
    
    Removed:
        leave_bags_at_home : Icon msg
```

**Comment by erlandsona** [comment]
https://material-ui.com/components/material-icons/
Search github and this should pop up
![Screenshot_20201108-133113](https://user-images.githubusercontent.com/10421138/98481218-d2def380-21c6-11eb-8a7c-aad2f89acb0f.png)

**Comment by icidasset** [comment]
I don't think that's maintained by Google, is it?
I'm using the official website as the source, which does not have it: https://material.io/resources/icons/

**Comment by erlandsona** [comment]
Well hot damn! I use it everyday for work you'd think I'd know that but TIL! Sorry for the bother, carry on 👌
