### ISSUE TITLE
Removal of shared types module

### ISSUE THREAD

**Issue by mikeastock** [icidasset/elm-material-icons#6]
Quick question, in the latest version of this library the shared types have been removed. This caused us to no longer be able to integrate the package with our internal color module as we now need to provide a helper function to convert each type of icon color. Would you consider moving back to a shared type module for colors? Thanks!

Here's an example of what we use to have:

```elm
toMaterialIcon : Element.Color -> Coloring
toMaterialIcon color =
    color
        |> toColorLibColor
        |> Material.Icons.Color

-- Convert elm-ui color to avh4/elm-color
toColorLibColor : Element.Color -> Color
toColorLibColor color =
    let
        rgba =
            Element.toRgb color
    in
    Color.rgba rgba.red rgba.green rgba.blue rgba.alpha
```

**Comment by icidasset** [comment]
Will revert the changes 👍

**Comment by mikeastock** [comment]
Awesome! Thanks for the quick response!

**Comment by icidasset** [comment]
@mikeastock Made a new release https://package.elm-lang.org/packages/icidasset/elm-material-icons/7.0.0/ with ye olden `Types` module. Let me know if that works for you.

**Comment by mikeastock** [comment]
Works great! Thank you again!
