### ISSUE TITLE
Maybe small error in docs

### ISSUE THREAD

**Issue by pfiadDi** [icidasset/elm-material-icons#9]
Hi started using your library, great work.
I think there is a small error in your about docs:

Filled.offline_bolt 16 (Color <| Color.rgb 96 181 204)

Color.rgb only accepts floats between 0 and 1 - for your example to work you need **Color.rgb255**

Not a big deal :)

**Comment by icidasset** [comment]
Oh, you're totally right, thanks for reporting this!
